name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout sources"
      uses: actions/checkout@v1

    - name: "Setup Java"
      uses: actions/setup-java@v1
      with:
        java-version: 13

    - name: "Run Gradle build"
      run: |
        cd plugin
        chmod 755 gradlew
        ./gradlew build -Dci=true

    - name: "Zip build reports"
      if: failure()
      run: zip -r reports.zip **/build/reports

    - name: "Upload build reports"
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: reports
        path: reports.zip

    - name: "Set PLUGIN_VERSION environment variable"
      run: |
        cd plugin
        ::set-env name=PLUGIN_VERSION::$(./gradlew --quiet printVersion)

    - name: "Publish to Gradle Plugin Portal"
      if: github.ref == 'refs/heads/release'
      run: |
        cd plugin
        ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
